# Generated by Django 4.1.7 on 2024-02-15 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_delete_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 15, 15, 25, 58, 945426)),
        ),
    ]
