# Generated by Django 4.1.7 on 2024-03-03 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 3, 9, 16, 4, 808698)),
        ),
    ]
