# Generated by Django 4.1.7 on 2024-03-06 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 22, 16, 35, 973319)),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
