# Generated by Django 4.1.7 on 2024-04-04 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_event_date_alter_event_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 20, 3, 31, 28894)),
        ),
    ]
