# Generated by Django 4.1.7 on 2024-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
