# Generated by Django 4.1.7 on 2024-02-04 08:31

import business.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('citiz_front_image', models.ImageField(upload_to=business.models.business_directory_path)),
                ('citiz_back_image', models.ImageField(upload_to='business_images/')),
                ('optional_docs1_image', models.ImageField(blank=True, null=True, upload_to='business_images/')),
                ('optional_docs2_image', models.ImageField(blank=True, null=True, upload_to='business_images/')),
                ('optional_docs3_image', models.ImageField(blank=True, null=True, upload_to='business_images/')),
                ('description', models.TextField()),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this business is verified or not. Unverified users cannot receive payments and are not displayed as business users.', verbose_name='verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
