# Generated by Django 4.1.7 on 2024-01-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='desccription',
            new_name='description',
        ),
    ]
