# Generated by Django 4.1.7 on 2024-01-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_rename_desccription_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this business is verified or not. Unverified users cannot receive payments and are not displayed as business users.', verbose_name='verified'),
        ),
    ]
