# Generated by Django 4.1.7 on 2024-02-03 07:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_business_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='business_images/'), blank=True, null=True, size=None),
        ),
    ]
