# Generated by Django 4.1.7 on 2024-03-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
