# Generated by Django 4.1.7 on 2024-04-04 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_key', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('is_logged_in', models.BooleanField(default=True, verbose_name='logged in')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
